version: "3.8"

services:
  db:
    image: postgres:16
    container_name: server-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: server-api-1
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
